### ISSUE TITLE
Edge Beta (v91), Cannot turn on screen capturing

### ISSUE THREAD

**Issue by SilentException** [gioxx/MarvellousSuspender#105]
* Extension version: 7.1.6.2
 * Browser name & version: Edge 91.0.864.19 (Official build) beta (64-bit)
 * Operating system & version: Windows 10, 21H1 (19043.964)

In extension options, selecting "Capture top of screen only" or "Capture entire page" fails to "Disabled" choice.
Would be nice to have it in Edge as well. Thanks!
Oh, and option "Apply Chrome's built-in memory-saving when suspending" doesn't seem to relevant for Edge, I think. It has it's own tab suspending thing, which I don't really like frankly.

**Comment by gioxx** [comment]
Ciao @SilentException , for screenshot problem please check this bug and try to enable with workaround: https://github.com/gioxx/MarvellousSuspender/issues/81

For possible enhancement thanks, we will evaluate them for future versions of the extension 😄

**Comment by SilentException** [comment]
Hey @gioxx thanks for letting me know. I was searching issues for keyword "Edge" as screen capturing works in my Chrome installation (store version) :)
For sure the workaround works, giving the file access, I get a popup for additional permission and screen capturing works in Edge as well! I will close this one as you already have #81 opened.
