### ISSUE TITLE
Recover suspended tabs after onetab

### ISSUE THREAD

**Issue by ghost** [gioxx/MarvellousSuspender#108]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: v7.1.6.2
 * Browser name & version: chrome 90.0.4430.212 (Official Build) (64-bit)
 * Operating system & version: Ubuntu 21.04
When using OneTab to share tabs, suspended tabs aren't unsuspend-able on a different machine with the same extension

**Comment by nfultz** [comment]
This would have to be fixed in OneTab - however, it's not an open source project.

**Comment by ghost** [comment]
Gotcha, although it would be nicer to get it as a feature within this extension instead.
