### ISSUE TITLE
In Chrome, I would like it to retain the groups of saved sessions

### ISSUE THREAD

**Issue by PauloFranc** [gioxx/MarvellousSuspender#109]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: v7.1.6.2
 * Browser name & version: Chrome 90.0.4430.212
 * Operating system & version: Windows 10 20H2 (compilation 19042.985)

Hello,
I use the grouping of tabs recently introduced in Chrome and, when I save a session with groups, when I later restore it, the groups aren't there anymore.

Thanks

**Comment by PauloFranc** [comment]
Hello,
I use the grouping of tabs recently introduced in Chrome but if I save a session, when I later restore it, the groups aren't there anymore.

Thanks

**Comment by gioxx** [comment]
#76, actually work in progress and already set for TMS 7.1.6.3.
