### ISSUE TITLE
Auto Sync backup/session with timer

### ISSUE THREAD

**Issue by tripathi-abhishek** [gioxx/MarvellousSuspender#115]
This is a feature request with which we will be able to continuously sync the session dynamically.
Let's say I have 21 tabs suspended in 2 or more windows, sessions are created I know but I would like to be able to have them exported continuously (syncing) with a file(text file in our case' which can have any location in the PC).

Basically the same export session feature, not manually but automatically after every unit of time (eg: 2 min, 10 min, 15 min etc)

Extension version: 7.1.6.2
Browser name & version: Chrome & Version 91.0.4472.77 (Official Build) (64-bit)
Operating system & version: Windows 10 Pro & 21H1

**Comment by baz357** [comment]
This sounds more like a feature Session Buddy (https://chrome.google.com/webstore/detail/session-buddy/edacconmaakjimmfgnblocblbcdcpbko) might get some day. It's _very_ (and maybe too) specific for a _suspender_ extension.

**Comment by gioxx** [comment]
+1 on @baz357 comment.

**Comment by tripathi-abhishek** [comment]
> This sounds more like a feature Session Buddy (https://chrome.google.com/webstore/detail/session-buddy/edacconmaakjimmfgnblocblbcdcpbko) might get some day. It's _very_ (and maybe too) specific for a _suspender_ extension.
