### ISSUE TITLE
Request: Scroll to last position after restore

### ISSUE THREAD

**Issue by GetoXs** [gioxx/MarvellousSuspender#117]
Thanks for the new extension I use it since beginning. 
I have an idea, it would be much useful to scroll to the last position after restore tab. 
Very useful if you was in the middle of the article and forget about it or other tabs distract you.
Just an idea, maybe sb include code to it :) 

Cheers!

**Comment by gioxx** [comment]
Duplicated: #131 (also duplicated of #85 )
