### ISSUE TITLE
[Bug] "Instantly suspend when system memory gets very low" doesn't respect "Never suspend tabs that contain unsaved form inputs"

### ISSUE THREAD

**Issue by frykauf** [gioxx/MarvellousSuspender#118]

**Comment by napolux** [comment]
The conflict between the "suspend when we have low memory" and the "do not suspend when there's unsaved form inputs"  should always be solved in favor of the first one.

We can consider the priority change in a future enhancement.

**Comment by ossilator** [comment]
that's a very strange choice - you're preferring guaranteed data loss over possible data loss?
