### ISSUE TITLE
Suspicious domain & Review

### ISSUE THREAD

**Issue by JesusAtheist** [gioxx/MarvellousSuspender#12]
https://github.com/gioxx/MarvellousSuspender/blob/61605c77670287f6a998205cde579d6d17ce2c17/src/js/background.js#L1185
Is this function still relevant in current situation?
Also would be good to verify other XMLHttpRequest.

**Comment by derSascha** [comment]
After removing the notice code, the content policy should be changed too:
https://github.com/gioxx/MarvellousSuspender/blob/1ee1b0b084647129250366f33b4a7b3066dc6755/src/manifest.json#L47

**Comment by Technetium1** [comment]
I second the request to change content security policy.

**Comment by SnirBroshi** [comment]
Why do we need `https://stats.g.doubleclick.net` in the CSP? is google analytics embedding it inside?

And why `data:`? Am I misunderstanding how CSP works?

Shouldn't we remove google analytics as well to move to manifest v3?

**Comment by gioxx** [comment]
I really want to thank you all for the feedback you are giving me. One step at a time I am sure we will be able to improve this extension.

Take a look: https://github.com/gioxx/MarvellousSuspender/commit/c61f31e50353c4d6308f024400e6e96d3f58e646

**Comment by Technetium1** [comment]
@gioxx Great job! You should be able to remove Metrics now I think... Not sure what legitimate purpose they serve(d), but please don't blindly merge the following removals without testing :)

Also, there is a [new html2canvas here](https://html2canvas.hertzen.com/dist/html2canvas.min.js), but that's probably not urgent, [although there are a LOT of changes](https://github.com/niklasvh/html2canvas/compare/v1.0.0-alpha.10...v1.0.0-rc.7) I don't know if it's to warrant opening a new issue to get it bumped.

https://github.com/gioxx/MarvellousSuspender/blob/bff2ec884d8ab40b4b5d1371491b617aa59a530a/src/js/background.js#L37
https://github.com/gioxx/MarvellousSuspender/blob/bff2ec884d8ab40b4b5d1371491b617aa59a530a/src/js/background.js#L142-L144
https://github.com/gioxx/MarvellousSuspender/blob/bff2ec884d8ab40b4b5d1371491b617aa59a530a/src/js/background.js#L1742-L1748
https://github.com/gioxx/MarvellousSuspender/blob/bff2ec884d8ab40b4b5d1371491b617aa59a530a/src/js/gsSession.js#L754-L800
https://github.com/gioxx/MarvellousSuspender/blob/bff2ec884d8ab40b4b5d1371491b617aa59a530a/src/js/gsSession.js#L836
https://github.com/gioxx/MarvellousSuspender/blob/bff2ec884d8ab40b4b5d1371491b617aa59a530a/src/js/gsStorage.js#L31
https://github.com/gioxx/MarvellousSuspender/blob/bff2ec884d8ab40b4b5d1371491b617aa59a530a/src/js/gsStorage.js#L382-L411

* Marking relation to https://github.com/gioxx/MarvellousSuspender/issues/23 for visibility

**Comment by cowbert** [comment]
> Also, there is a [new html2canvas here](https://html2canvas.hertzen.com/dist/html2canvas.min.js), but that's probably not urgent, [although there are a LOT of changes](https://github.com/niklasvh/html2canvas/compare/v1.0.0-alpha.10...v1.0.0-rc.7) I don't know if it's to warrant opening a new issue to get it bumped.

We don't have to be on the bleeding edge all the time. If it ain't broke...

**Comment by Technetium1** [comment]
@cowbert I agree, no need to be on the bleeding edge without reason. Just pointing it out.

**Comment by gioxx** [comment]
All metrics deleted and "first code revised".
Next step: comment functions, cleanup & optimize code with @sherkot 🤟🏻

**Comment by lastmetroid** [comment]
Is The Marvellous Suspender 7.1.6.1 safe to use?

**Comment by Technetium1** [comment]
@makedir in my opinion yes.

**Comment by JesusAtheist** [comment]
There is no 'eval' anything in the code. And there only places where external requests happen is getAndEncode() in dom-to-img.js and in html2canvas lib. Maybe there are others ways to hide malicious code, but i don't know. So you can delete this two files and be sure you are in safe. (but you will lose screen capturing feature)
