### ISSUE TITLE
system crash when suspending MANY tabs

### ISSUE THREAD

**Issue by alidan** [gioxx/MarvellousSuspender#126]
* Extension version: v7.1.6.2
 * Browser name & version: 91.0.4472.77
 * Operating system & version:win 7 64

not 100% sure if this is tms, but I had the system blue screen once when suspending 700~ tabs that could have been due to an uptime of 90~ days

had another blue screen when suspending around 100~ tabs with a sub week uptime. both times the system went down mid suspending tabs, so for now I linked system crashing with this.

**Comment by Masamune3210** [comment]
There is almost nothing that chrome could do to cause a blue screen so I think you might be seeing a symptom more than a cause here. User-mode programs really cant do much do cause one if Windows is functioning correctly

**Comment by ossilator** [comment]
yes, it's most likely triggering a bug in the graphics driver or something like that.

**Comment by napolux** [comment]
Probably not TMS related
