### ISSUE TITLE
tab gets suspended while working on a long text

### ISSUE THREAD

**Issue by nimiboid** [gioxx/MarvellousSuspender#127]
* Extension version: v7.1.6.2
 * Browser name & version: Version 91.0.4472.77 (Official Build) (64-bit)
 * Operating system & version: win10

Tab gets suspended while working on longer text and thus losing all text entered.

Steps to reproduce
1) Go to a page where you can enter text in a textarea, e.g. github issue or jira or runscrum
2) Start entering text
3) Enter text for as long as the automatic suspension setting
4) See how the tab gets suspended while entering text
5) Unsuspend and see all your input lost

Expected behaviour
I would love for Marvellous to detect whether a textarea has focus and prevent automatic suspension. 
Or even better: I would love for Marvellous to detecxt whether a form is changed - well, any of its form controls - and prevent automatic suspension. 

In my opinion data loss is worse then memory consumption.

**Comment by PatrickL546** [comment]
Is "Never suspend tabs that contain unsaved form inputs" enabled?

I see this when I typed on a text box.

![image](https://user-images.githubusercontent.com/75874561/121236075-901bf180-c863-11eb-9efd-18d0b02636f6.png)

**Comment by nimiboid** [comment]
Sorry, forgot to mention this - yes, setting is enabled. 

I think I've narrowed it further down. It happens on a CKEditor field. Maybe this is the real reason.

**Comment by Gyumaou** [comment]
I have the same issue, in fact the tab suspended while I was actively typing a comment on a different issue. The option to not suspend with active form inputs is enabled, but in the menu TMS doesn't detect that being the case. I am using the latest version  of Chrome 91.0.4472.77 (Official Build) (64-bit) on Win10.
![image](https://user-images.githubusercontent.com/6417525/121401030-2decea80-c950-11eb-8cce-d6a5a03cd9f7.png)

**Comment by PatrickL546** [comment]
I installed TGS 7.1.6 and it seems to be working there

![image](https://user-images.githubusercontent.com/75874561/121447979-c7be9280-c964-11eb-87a4-fadc671808ee.png)

**Comment by owenblacker** [comment]
I'm running Marvellous Suspender 7.1.6.2 and had exactly this problem while writing a long Jira ticket earlier today. I'm also seeing it in this tab while I'm typing this.

The extension has loaded ok right now but for Jira earlier, I had opened the tab while the window was on a secondary monitor, and had the "not loading" experience, which I'm sure I've seen a ticket for but can't find right now — even after the page has finished loading, clicking the extension icon gives me this popup: 
![Marvellous Suspender autosuspend fail 1](https://user-images.githubusercontent.com/376642/125689175-7a443d09-50a6-491b-a0fc-386ecfb0ef13.png)

After a while, the popup seems to time-out and change to:
![Marvellous Suspender autosuspend fail 2](https://user-images.githubusercontent.com/376642/125689187-0b06aca5-b976-469d-b780-3119fd30efdd.png)

**Comment by sherkot** [comment]
Fixed with 350ec60505d79df7dffe1b841a8cd9b974636ef8 (Permissions fixes). To be released in 7.1.6.3
