### ISSUE TITLE
Extension should follow per system's theme setting.

### ISSUE THREAD

**Issue by kamekku14** [gioxx/MarvellousSuspender#129]
Sure, Windows 10 has dark mode, but should let this extension follow the system's theme setting? I'm not sure if it's very useful or not...

 * Extension version: v7.1.6.2
 * Browser name & version: Google Chrome, version 91.0.4472.101 (Official Build) (64-bit)
 * Operating system & version: Windows 10 Pro, version 21H1 (build 19043.985)

**Comment by gioxx** [comment]
Duplicated: https://github.com/gioxx/MarvellousSuspender/issues/67
