### ISSUE TITLE
Auto Scroll to Last Screen Position - after restoring of a tab(s) - still works in v7.1.6.1

### ISSUE THREAD

**Issue by seb36c** [gioxx/MarvellousSuspender#131]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: The Marvellous Suspender 7.1.6.2
 * Browser name & version: Microsoft Edge	91.0.864.54 (Official build) (64-bit) & Chrome  91.0.4472.114 (Official Build) (64-bit)
 * Operating system & version:  Windows 10 v1902                            

**Scroll to last position after restoring a tab(s) -- this still works in version 7.1.6.1** -- Any way to merge it into the latest version (7.1.6.2) and all future versions?  Version 7.1.6.2 always sets the URI - position screen location to **(&pos=0)**  As, this was one important reason we all loved the original **"The Great Suspender"** as it allowed us to save time and get back to what we were working on, saving lots of valuable wasted labor time. 

Thanks so very much, for keeping up this amazing extension for our browsers.

**Comment by gioxx** [comment]
Duplicated: https://github.com/gioxx/MarvellousSuspender/issues/85
