### ISSUE TITLE
Tab screenshot not working

### ISSUE THREAD

**Issue by rust2** [gioxx/MarvellousSuspender#134]
Page screenshot is not working. When I trying to choose "Only top of page" or "Whole page" it just changes back to "Disabled" (sry if unclear but I'm using Russian language and can't tell what exactly I mean)
Video link [ru]: https://youtu.be/J018H_hgdjo

 * Extension version: v7.1.6.2
 * Browser name & version: Chrome 90.0.4430.85
 * Operating system & version: Windows 10 OS Version 1909 (Build 18363.1139)

**Comment by SchoofsKelvin** [comment]
Had the same issue. After looking around for a minute, I was able to fix it by right-clicking the extension icon, selecting `Manage extensions` and finally enabling the `Allow access to file URLs` option.

**Comment by rust2** [comment]
Thank you for solution
