### ISSUE TITLE
Unable to select/use non-default option for "Screen capturing"

### ISSUE THREAD

**Issue by jyscao** [gioxx/MarvellousSuspender#141]
* Extension version: 7.1.6.2
 * Browser name & version: Chrome Version 93.0.4577.63 (Official Build) (arm64)
 * Operating system & version: macOS 11.5.2 (arm64)

![image](https://user-images.githubusercontent.com/12605746/133914580-3c550d6d-1ac0-4ea2-9e3c-dbf09df2cc17.png)

When I try to select either "Capture top of screen only" or "Capture entire page" from the "Screen capturing" dropdown above, it would always set the value back to "Disabled" after I select it. And indeed I'm unable to use this functionality, which I know worked well on my Ubuntu desktop.

**Comment by JediRhymeTrix** [comment]
https://github.com/gioxx/MarvellousSuspender/issues/106#issuecomment-841890845

Please try the workaround mentioned here. I believe the fix will be available with the next release.

**Comment by jyscao** [comment]
@JediRhymeTrix great, thanks for the heads up!

**Comment by mattalxndr** [comment]
Came here with the same problem.

I know you already confirmed it but I'll leave the screencast anyway:

https://user-images.githubusercontent.com/250466/142757463-c18ac9df-ee75-46bd-afae-2e1e14bc0a2b.mp4
