### ISSUE TITLE
[BUG] Suspending Youtube videos

### ISSUE THREAD

**Issue by qwewer0** [gioxx/MarvellousSuspender#142]
### Description

Suspending and unsuspending a youtube video does not continues the video where it was suspended (unlike how [The Great Suspender](https://github.com/aciidic/thegreatsuspender-notrack) does)

Please complete the following information when submitting a feature request or bug report.
 * Extension version: 7.1.6.2
 * Browser name & version: Chrome Version 94.0.4606.54
 * Operating system & version: Windows 10, 10.0.19043 Build 19043

**Comment by idsulik** [comment]
It's because the extension hasn't access to the site data.
@gioxx , why r u move host access from permissions to optional_permissions? 
If you did it, I think you should request the access

**Comment by idsulik** [comment]
@qwewer0 , you can follow instructions from README **Install as an extension from source**, but before load extension, open **manifest.json** and add this line right after **cookie**(permissions block):
**"https://www.youtube.com/"**

**Comment by ebnc** [comment]
This feature is definitely needed.
