### ISSUE TITLE
"Not now" Button & associated shortcut not working

### ISSUE THREAD

**Issue by amidstdebug** [gioxx/MarvellousSuspender#143]
- v7.1.6.2
 - Microsoft Edge Version 94.0.992.38 (Official build) (64-bit)
 - Edition	Windows 10 Home
- Version	21H1
- Installed on ‎1/‎3/‎2021
- OS build 19043.1052
- Experience Windows Feature Experience Pack 120.2212.2020.0

The 'tab will suspend now. Not now' button does not work when pressed, also the shortcut for it also doesn't work. Tab still gets suspended

**Comment by ryan6416** [comment]
Any workaround/fix or update on this?

**Comment by gioxx** [comment]
https://github.com/gioxx/MarvellousSuspender/issues/86
