### ISSUE TITLE
Suspended tabs don't have focus

### ISSUE THREAD

**Issue by twio142** [gioxx/MarvellousSuspender#150]
I use vim-styled hotkeys in Chrome and would also like to navigate suspended tabs using the same hotkeys. What I wish for is to be able to switch fluently between all tabs, no matter suspended or not, using the same single key. 

So I added some event listeners to `gsSuspendedTab.js`:
- `h` to previous tab, 
- `l` to next tab, 
- `x` to close tab, and
- `space` to unsuspend tab.

But the problem is that a suspended tab has no focus, so I always need to press `tab`, once or twice, before those hotkeys. Would it be possible to let a suspended tab automatically gain focus when it's activated?

**Comment by russ-travix** [comment]
I'm sure the Focus thing is possible, but I'm only reading this project, not a part of it ... but I have to say, your Vim hotkeys sound fascinating, do you have a blog page about this, or something? I would love to know more! Sounds very appealing to me, as I currently have over 800 suspended tabs and every so often I have a clear out, but it's very time consuming!
Thanks!

**Comment by twio142** [comment]
@russ-travix not sure what exactly you're asking for, but you can check out the [Vimium extension](https://github.com/philc/vimium). The extension doesn't work on suspended tabs though.
