### ISSUE TITLE
Temporally stop of automatic suspension not working

### ISSUE THREAD

**Issue by MW-J97** [gioxx/MarvellousSuspender#160]
* Extension version: 7.1.6.2
 * Browser name & version: Vivaldi 5.1.2567.38 (Official Build) (64-bit) 
 * Operating system & version: Windows 10 Version 21H2 (Build 19044.1466)

When I open the extension and tab on "Not now" to temporally stop of automatic suspension, That doesn't work. It even doesn't respond.

**Comment by gioxx** [comment]
https://github.com/gioxx/MarvellousSuspender/issues/86
