### ISSUE TITLE
Chrome crashes randomly

### ISSUE THREAD

**Issue by flawnn** [gioxx/MarvellousSuspender#162]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: 7.1.6.2
 * Browser name & version: 
![image](https://user-images.githubusercontent.com/19386703/157297484-51bf8103-a7d0-4d15-bc06-8b268b4baccd.png)
 * Operating system & version: Windows 11
 
Hello everyone,
my Chrome browser has been experiencing crashes for already a year or so. I literally tried everything to find out what it was (seems not to be the browser's fault or the systems), so I have the doubt that it's actually this extension causing the crashes. I only have a debug log but I couldn't really get something out of it. Please help me find out what it is as it is really annoying...

Thanks in advance

[chrome_debug.log](https://github.com/gioxx/MarvellousSuspender/files/8208552/chrome_debug.log)

**Comment by ossilator** [comment]
firstly, it's impossible for any extension to be the _cause_ of browser crashes. at worst, it may be a _trigger_ for what is inevitably a bug in the browser or system.

secondly, why do you suspect this extension? does uninstalling it consistently avoid the problem, even taking confounding variables into account (e.g., the fact that you'll likely have fewer open tabs, etc.)?

**Comment by flawnn** [comment]
> firstly, it's impossible for any extension to be the _cause_ of browser crashes. at worst, it may be a _trigger_ for what is inevitably a bug in the browser or system.
> 
> secondly, why do you suspect this extension? does uninstalling it consistently avoid the problem, even taking confounding variables into account (e.g., the fact that you'll likely have fewer open tabs, etc.)?

Yes, when disabling the extension the issue didn't seem to appear any more. I suspect it might have to do with RAM Allocation for the extension and then being the trigger to closing chrome. To be more precise on the "crash": Chrome just closes as a whole as if I would terminate the process over task manager.

Might be also that I have too much tabs open but the extension copes pretty well with it and chrome's RAM usage is only at round about 2 GB with me having more than 100 tabs open. Might be also actually a limitation of chrome that when surpassing a threshold of open tabs it just straight up crashes? I couldn't find anything on that at least in the world wide web.

Also if anyone might have experienced this issue too, please let me know as it's really hard to pinpoint the issue on to something with high accuracy. The next best I could come up with was posting an issue here although the extension might not be the direct cause.

**Comment by ossilator** [comment]
dunno. given the persistence of the problem, the primary suspects are:
- hardware issue, like bad ram or inadequate cooling. there are stress-testing tools for that.
- (graphics) driver issue. stress-testing might help here as well, though it's somewhat unlikely.

i don't think that chrome is exiting "just so" - it probably reacts this way to some critical process crashing away, or something. you'll need to find that yourself in the megabytes of logs, possibly after enabling even more debug output. maybe the system log contains a relevant event.

**Comment by Technetium1** [comment]
@flawnn I agree with ossilator's above comment. You can start troubleshooting by completely removing all traces of this browser from your computer (this includes leftovers after uninstall) and doing a clean reinstall, as well as confirming your operating system is both intact and fully updated. I believe there to be an issue with the browser as your update mechanism has failed per the newest version on their [download page](https://www.srware.net/iron/).

If one of many tabs, or an extension crashes, the parent process will not exit, which leads me to believe it's an issue outside of extensions. There is not a limit on how many windows/tabs you can have open within Chromium, so that can be ruled out.

A side note: Your browser is woefully out of date, **_please_** consider using an updated alternative in the meantime you have these issues.

**Comment by flawnn** [comment]
> @flawnn I agree with ossilator's above comment. You can start troubleshooting by completely removing all traces of this browser from your computer (this includes leftovers after uninstall) and doing a clean reinstall, as well as confirming your operating system is both intact and fully updated. I believe there to be an issue with the browser as your update mechanism has failed per the newest version on their [download page](https://www.srware.net/iron/).
> 
> If one of many tabs, or an extension crashes, the parent process will not exit, which leads me to believe it's an issue outside of extensions. There is not a limit on how many windows/tabs you can have open within Chromium, so that can be ruled out.
> 
> A side note: Your browser is woefully out of date, **_please_** consider using an updated alternative in the meantime you have these issues.

Does anybody of you know how I potentially could find the cause of it crashing? I tried checking Window's Event Viewer as well as the chrome_debug.log, but both don't give me the slightest hint what it could be (if we rule out extensions). Could it be a faulty chrome profile theoretically? If yes, it should be somehow be recognizable from the debug log though...

And yeah I updated but I don't think that it got magically fixed by now, there must be another issue behind this.

**Comment by Technetium1** [comment]
I'm not sure this is the place for that. You can contact me via my profile if you'd like. If Windows probably run `DISM /Online /Cleanup-Image /RestoreHealth`, reboot, and run `sfc /scannow`, then reboot and rescan with both until sfc reports no errors.
