### ISSUE TITLE
Chrome crashing - STATUS_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by Infinitay** [gioxx/MarvellousSuspender#163]
* Extension version: `7.1.6.2`
 * Browser name & version: `Google Chrome Version 99.0.4844.51 (Official Build) (64-bit)`
 * Operating system & version: `Windows 10 21H2 (Build 19044.1586)`

Recently TMS has started to crash my Chrome with the following issue,

> Aw, Snap!
> Something went wrong while displaying this webpage.
> Error code: STATUS_ACCESS_VIOLATION

and a corresponding desktop notification from Google Chrome with the label:

> The Marvellous Suspender has crashed. Click this balloon to reload the extension.

My Chrome is up to date. I tried closing all processes and restarting Chrome. I have tried restarting my PC. The issue happens with or without incognito. The issue happens on one tab or many, suspended or not. In the case of it not being suspended, after a few minutes of inactivity, not the same amount as set in the settings to auto-suspend, Chrome will still crash.

What's odd is that this issue is not happening on my other PC despite having a near-identical setup with the only difference being my Window's version (20H2 versus 21H2).

I tried debugging via `--enable-logging --v=1` but I did not notice anything of use within the debug log.

**Comment by Masamune3210** [comment]
Just a heads up, unless something goes seriously wrong in the browser, a extension will never be able to cause a full browser crash
