### ISSUE TITLE
Función "Not Now" No funciona.

### ISSUE THREAD

**Issue by PepeParada** [gioxx/MarvellousSuspender#186]
Hola. Tengo la versión v7.1.6.3. Utilizando Chrome y Brave (ambos). Windows 7 x64.

Descargué esta genial extensión desde Chrome Store, y noté que la función "No ahora" (Not Now) no funciona. Ni siquiera cambia de color ni de apariencia al hacer click sobre el botón. En cambio, si descargo la extensión desde aquí, Github, y la cargo manualmente, el botón sí cambia de apariencia al hacer click sobre él, pero aún así no funciona. 

Más allá de esto, la extensión es buenísima. Agradezco al creador porque utilizo mucho esta extensión y es muy útil para mí. 
Saludos.

**Comment by mendelsphotography** [comment]
Esto podría ser un duplicado de #185 y #188 si es que hay una solución temporal para ello, incluidas las ventanas.

**Comment by gioxx** [comment]
Duplicated: #185 #188
