### ISSUE TITLE
Feature Request: A Dark Mode for Suspended tabs and UI

### ISSUE THREAD

**Issue by WolvenSpectre** [gioxx/MarvellousSuspender#19]
Pretty much all in the title... the only thing I am missing from TGS, although thumbnail/preview would be nice as well but not a must.

**Comment by hoax92** [comment]
hi. all this seems to exist already. or am i misunderstanding something?

screenshot from 7.1.6.1: [https://i.imgur.com/HiUUQnu.png](https://i.imgur.com/HiUUQnu.png)

**Comment by Technetium1** [comment]
An option for full black would be nice, so it could be more OLED friendly (`#000000`)

**Comment by gioxx** [comment]
Work in progress: https://github.com/gioxx/MarvellousSuspender/commit/7259acaee6a6b22bce43034c2b0c2d92eee92536

**Comment by WolvenSpectre** [comment]
My browser wasn't showing the scrollbar on the right so on my 1080p  
monitor it didn't look like there were other options.  Vivaldi it is  
showing now.

*facepalm*

Thanks for the response.

On Sun, 07 Feb 2021 11:04:07 -0600, hoax92 <notifications@github.com> wr
