### ISSUE TITLE
Restore Gruntfile.js and other files required to build a crx

### ISSUE THREAD

**Issue by derSascha** [gioxx/MarvellousSuspender#20]
Thanks for the cleaned fork!

Can we add the files required to create a crx build e.g. the package and Grundfile? Would you accept an PR on this?

**Comment by gioxx** [comment]
> 
> 
> [...] Would you accept an PR on this?

Yes, please!

**Comment by derSascha** [comment]
Great, created PR #22

**Comment by gioxx** [comment]
Thanks!
