### ISSUE TITLE
Screen Capturing

### ISSUE THREAD

**Issue by clydo** [gioxx/MarvellousSuspender#207]
Hey! 
I can't make working the screen capturing feature, when i chose something else than "disabled" it instant goes back to "disabled", no matter if i pick "capture top of screen only" or "capture entire page"... In case you have any idea how to/why ?
![MS](https://github.com/gioxx/MarvellousSuspender/assets/28127165/b0828d9b-1b28-4e94-8b95-b088f4f06be6)

**Comment by oasaph** [comment]
It's a tab permission problem
![image](https://github.com/gioxx/MarvellousSuspender/assets/20308482/043612a6-7565-43ee-847a-8605c39fd33b)

**Comment by Technetium1** [comment]
@clydo have you enabled access to file URLs? `chrome://extensions`
![image](https://github.com/gioxx/MarvellousSuspender/assets/9877150/0433fcbe-c7b3-41e1-9209-f717d277ca21)

**Comment by clydo** [comment]
> @clydo have you enabled access to file URLs? `chrome://extensions` ![image](https://user-images.githubusercontent.com/9877150/240437510-0433fcbe-c7b3-41e1-9209-f717d277ca21.png)

Well, thank you, it worked, don't know why this wasn't ticked (if it were supposed to be)!
