### ISSUE TITLE
Another fork of Great Suspender

### ISSUE THREAD

**Issue by SleepDaemon** [gioxx/MarvellousSuspender#226]
found this https://github.com/aciidic/thegreatsuspender-notrack on chrome web store. While webstore said it got updated just back in October, github repo doesnt say the same.

I wanna hear your opinion on this fork, is it better? if so in what ways is it better? are their any downside or red flags?

**Comment by gioxx** [comment]
https://github.com/gioxx/MarvellousSuspender/issues/217
