### ISSUE TITLE
Lost all tabs!

### ISSUE THREAD

**Issue by jivatneet** [gioxx/MarvellousSuspender#243]
I'm using Marvellous suspended on Edge and I lost all my tabs as soon as I uninstalled the extension without any warning! I lost a ton of tabs on two windows and would appreciate any help accessing them.

**Comment by cmckni3** [comment]
Same happened to me. No way to restore the tabs either since they were closed by the extension.

**Comment by Technetium1** [comment]
@cmckni3 if you are testing the new version, consider posting at https://github.com/gioxx/MarvellousSuspender/discussions/254
