### ISSUE TITLE
I seen has a translate trad Chinese but extension interface still English...

### ISSUE THREAD

**Issue by kenxran** [gioxx/MarvellousSuspender#26]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: v7.1.6.1
 * Browser name & version: Google 88.0.4324.150 (Stable version) (64 bits)
 * Operating system & version: Windows 10.0.17134.885 (64 bits)

I seen has a translate trad Chinese but extension interface still English...
A bit strange...

![image](https://user-images.githubusercontent.com/11792366/107109765-e52c0480-687d-11eb-8302-92d45ceb25d9.png)

**Comment by gioxx** [comment]
Hello @kenneth-ran, can you please download this test version of TGS, load on your Chrome and tell me if you can see the Chinese localization? https://www.dropbox.com/t/pyPTrQDECWivGciq

You have to go to extensions management on Google Chrome, enable Developer Mode and load an unpacked extension, then navigate to TGS_Test folder.

Thanks a lot in advance.
Giovanni

**Comment by gioxx** [comment]
Ciao @kenneth-ran, I have used locale codes taken from https://developer.chrome.com/docs/webstore/i18n/#localeTable
zh_CN | Chinese (China)
zh_TW | Chinese (Taiwan)

Is this an error?
Thanks in advance.
Giovanni.
