### ISSUE TITLE
Any way to import from TGS, now that TGS is disabled?

### ISSUE THREAD

**Issue by q00u** [gioxx/MarvellousSuspender#3]
Is there an upgrade path from The Great Suspender?

The Great Suspender was disabled by the Chrome store today for containing malware, so there's no access to export from the extension itself.

**Comment by anish749** [comment]
Press back on the tabs that was suspended by tgs, then wait for tms to suspend it back again.

**Comment by q00u** [comment]
I don't mean for individual tabs. I have 2000+ tabs. Is there a way to import the TGS _session_ into TMS?

Also, pressing back does not always work. First of all, it does not appear to give you the suspended page, but the one prior to it in the history. And if there's NO prior page, you can't go back.

**Comment by ultrafez** [comment]
It might be possible for the author of TMS to add a feature to the extension to find all open tabs that were suspended using TGS, extract the URL from the "suspended" URL, and then suspend them using TMS.

I've never written a Chrome extension, but from having a quick search online, it seems to be possible to [get the URLs of all the open tabs](https://stackoverflow.com/a/16185419/172666).

If @gioxx implemented this fairly quickly, then it would provide a good migration experience for all of the users of TGS who now have loads of unsuspendable tabs.

**Comment by wchristian** [comment]
i've explained how to load the tabs again in this issue: #7

**Comment by Kyu** [comment]
> I've never written a Chrome extension, but from having a quick search online, it seems to be possible to get the URLs of all the open tabs.  

I tried to write such an extension, was blocked by [this chrome feature](https://stackoverflow.com/questions/49926865/chrome-extension-unchecked-runtime-lasterror-while-running-tabs-executescript)  

But this was my first attempt at writing a an extension, so maybe someone with more experience can do it

**Comment by alagos** [comment]
FWIW, check [this comment](https://github.com/greatsuspender/thegreatsuspender/issues/1263#issuecomment-773538665), it should work for a handful of pages to recover. 
Not sure about +2000 tags, but with enough time and patience...

**Comment by basilisk487** [comment]
@q00u try restarting Chrome, and re-enabling TGS - there is about a minute or so window of time before it gets blocked again, but that should be enough to export your session. Disabling your internet connection before restarting Chrome should give you more than enough time to export.

**Comment by q00u** [comment]
Unfortunately, due to having 2000+ tabs, it takes far more than a minute before I'm able to use Chrome after restarting.

Exporting the session only gives you the current page, not the history. It's _a_ solution, but not a _perfect_ solution.

For some reason, my other computer hadn't disabled TGS yet, and I was able to install TMS, and right-click-TGS-Unsuspend-all-tabs-in-all-windows, and voila! TGS can go away and I don't lose anything because nothing was suspended. Of course, that computer didn't have nearly as many tabs.

And alas, the disconnect-from-Internet technique is not ideal either, since unsuspending tabs with no network connection just gives me a lot of dead pages.

**Comment by ossie-git** [comment]
@q00u You can try this. A little manual but it works:

- extract Chrome's history (you can do this by running sqlite3 on the History file or you can use ChromeHistoryView if you are on Windows)
- extract lines in your history file that have the string "klbibkeccnjlkjkiokjodocebajanakg"
- extract the URL from these lines and save the list to a file
- import the list using this extension [Open Multiple URLs](https://chrome.google.com/webstore/detail/open-multiple-urls/oifijhaokejakekmnjmphonojcfkpbbh?hl=en)
- remove the "Open Multiple URLs" extension

**Comment by gioxx** [comment]
> 
> 
> If @gioxx implemented this fairly quickly, then it would provide a good migration experience for all of the users of TGS who now have loads of unsuspendable tabs.

Unfortunately I was unlucky like @Kyu because I'm a newbie with Chrome extensions development. At this time I can't write an importer from TGS but there are a lot of methods to migrate all tabs to TMS. Sorry and many thanks for all your suggestions and feedback!

**Developers**: feel free to make a pull request if you want to integrate an importer from TGS to TMS into the source code of this extension. All contributions are absolutely precious!

**Comment by AdrianKielbowicz** [comment]
You can get the URLs from:

C:\Users\%Username%\AppData\Local\Google\Chrome\User Data\Default\IndexedDB\chrome-extension_klbibkeccnjlkjkiokjodocebajanakg_0.indexeddb.blob

(look at the most recent folder with a randomly named file in it)

Formatting is crap so it takes time to get the URLs out but it is certainly doable. Not sure about 2000+ tabs, just done about a hundred and want to kill myself now!

**Comment by ultrafez** [comment]
Another method @q00u that might work for you, if the history methods discussed above don't work - from the "..." Chrome menu, you can choose Bookmarks -> "Bookmark All Tabs...", which saves them all into a folder, including the `chrome-extension://` URLs. You can then export these bookmarks as an HTML page using the Bookmark Manager, at which point you could extract all of the URLs en masse with a text editor.

**Comment by Technetium1** [comment]
PR that may help migrating: https://github.com/aciidic/thegreatsuspender-notrack/pull/3/files
@q00u maybe try https://github.com/greatsuspender/thegreatsuspender/issues/1263#issuecomment-774221150

**Comment by q00u** [comment]
That pull request looks great! Any chance of getting it for Marvelous Suspender as well?

**Comment by Technetium1** [comment]
Another solution to be aware of https://github.com/greatsuspender/thegreatsuspender/issues/1263#issuecomment-774300246

**Comment by JesusAtheist** [comment]
@ #42

**Comment by JesusAtheist** [comment]
#42
