### ISSUE TITLE
Suspension is kicking in when user is in the Debug Console

### ISSUE THREAD

**Issue by donnyv** [gioxx/MarvellousSuspender#40]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: 7.1.6.1
 * Browser name & version: Chrome v88.0.4324.150
 * Operating system & version: Win 10

Suspension is kicking in when user is in the Debug Console and its being used. It then wipes any data that was in the console window away.

**Comment by q00u** [comment]
How is the extension supposed to know whether or not the Debug Console is open?

Did you have "Never suspend active tab in each window" unchecked? Or, was the tab not active?

In the future, you can pin the tab (assuming you have the appropriate "Never suspend pinned tabs" option checked), or select "Never suspend this URL" from the right-click menu.

**Comment by donnyv** [comment]
I do have this checked. "Never suspend active tab in each window"

Never had this issue with the Great Suspender.

**Comment by gioxx** [comment]
> 
> 
> Never had this issue with the Great Suspender.

Strange because TMS 7.1.6.1 is totally based on TGS 7.1.6. The first version modified of TMS is the 7.1.6.2 not yet available on Chrome Store.

**Comment by donnyv** [comment]
I extended my time. Maybe in GS the time was longer before it suspended.
