### ISSUE TITLE
Maintaining and a question about Firefox.

### ISSUE THREAD

**Issue by Github852** [gioxx/MarvellousSuspender#41]
Hello! I have 2 questions regarding this fork.
@gioxx 
Do you plan on maintaining the extension? And perhaps adding new features?
Can/would you make a native Firefox version of the MarvellousSuspender?

**Comment by gioxx** [comment]
> 
> 
> Do you plan on maintaining the extension? And perhaps adding new features?

https://gioxx.org/2021/02/06/the-marvellous-suspender-hello-world/

>
>
> Can/would you make a native Firefox version of the MarvellousSuspender?

https://github.com/gioxx/MarvellousSuspender/issues/18

**Comment by Github852** [comment]
Thanks for the response! Well hopefully one day we will have it over to Firefox :) I might help in the future, too!
