### ISSUE TITLE
One click restore of tabs, which was suspended with another extension id (chrome.runtime.id)

### ISSUE THREAD

**Issue by JesusAtheist** [gioxx/MarvellousSuspender#42]
1. Just open extension's about page.
2. Change last part of url from options.html to debug.html 
3. Click on a 'claim all suspended tabs' (upper right corner);
4. All corrupted tabs will be unsuspend.

It could be useful for people who already saved a lot of suspended tabs in tab session extensions ([like this](https://github.com/sienori/Tab-Session-Manager)) or in bookmarks.
Would be good if it will be added to documentation.

**Comment by SWxEng** [comment]
good

**Comment by gioxx** [comment]
Done! 
https://github.com/gioxx/MarvellousSuspender/commit/58799687ef8cd397a0ca3c23658e4316ee09dcc7
