### ISSUE TITLE
Unknown script.

### ISSUE THREAD

**Issue by ghost** [gioxx/MarvellousSuspender#43]
![download](https://user-images.githubusercontent.com/19195873/107382694-16a80880-6ae8-11eb-908a-682d44b35da6.png)

This is a joke and not funny this site in the image is trusted. Is this a joke?

**Comment by gioxx** [comment]
Gsanalytics.js is the script that was used to collect anonymous statistics through Google Analytics and was already present in the old original extension (The Great Suspender). It is not a malware. In the new version of the extension that file doesn't even exist anymore (it will be released in the Chrome Store soon), you can check by yourself in the repository.

**Comment by Technetium1** [comment]
I can confirm there's no malware to be had there, simply some old analytics. I just downloaded the webstore CRX content and pasted to this repo set to an old tag. There is nothing dangerous there @tris543. If you're in doubt you can download the repository in it's current state and install that way, then you can see what changes and choose whether or not to update. Please consider changing the title to 'false positive' or something similar unless you've got some way to show that there is actually malware rather than a false positive. https://robwu.nl/crxviewer/crxviewer.html?crx=https%3A%2F%2Fchrome.google.com%2Fwebstore%2Fdetail%2Fthe-marvellous-suspender%2Fnoogafoofpebimajpfpamcfhoaifemoa 
Version I looked at on webstore: 
![image](https://user-images.githubusercontent.com/9877150/107388166-8952bd00-6ac3-11eb-8eb2-cd75a9a5a534.png)
![image](https://user-images.githubusercontent.com/9877150/107387671-0df10b80-6ac3-11eb-91a7-1dd5414eea13.png)

**Comment by ghost** [comment]
> Gsanalytics.js is the script that was used to collect anonymous statistics through Google Analytics and was already present in the old original extension (The Great Suspender). It is not a malware. In the new version of the extension that file doesn't even exist anymore (it will be released in the Chrome Store soon), you can check by yourself in the repository.

Sound like someone was using the old version TGS. I am sorry but i did forget to edit the post that the image was sourced from reddit. Right now everyone is on alert about what happen and some users are still yet to trust it. Dont worry i have change the title. Feel like a victim am sorry about that.

**Comment by ghost** [comment]
> I can confirm there's no malware to be had there, simply some old analytics. I just downloaded the webstore CRX content and pasted to this repo set to an old tag. There is nothing dangerous there @tris543. If you're in doubt you can download the repository in it's current state and install that way, then you can see what changes and choose whether or not to update. Please consider changing the title to 'false positive' or something similar unless you've got some way to show that there is actually malware rather than a false positive. https://robwu.nl/crxviewer/crxviewer.html?crx=https%3A%2F%2Fchrome.google.com%2Fwebstore%2Fdetail%2Fthe-marvellous-suspender%2Fnoogafoofpebimajpfpamcfhoaifemoa
> Version I looked at on webstore:
> ![image](https://user-images.githubusercontent.com/9877150/107388166-8952bd00-6ac3-11eb-8eb2-cd75a9a5a534.png)
> ![image](https://user-images.githubusercontent.com/9877150/107387671-0df10b80-6ac3-11eb-91a7-1dd5414eea13.png)

Look above thanks for looking btw.

**Comment by MeiRct** [comment]
> ![download](https://user-images.githubusercontent.com/19195873/107382694-16a80880-6ae8-11eb-908a-682d44b35da6.png)
> 
> This is a joke and not funny this site in the image is trusted. Is this a joke?

@tris543 I saw that you already took back your alert and apologized for it, but I want to explain to others that might come to this issue in the future:

Look carefully at the ID in the tooltip with the file path, next to the mouse pointer in the screenshot:
`klbibkeccnjlkjkiokjodocebajanakg`
This is the ID of the old malicious "The Great Suspender", which was probably kept disabled on that computer and wasn't removed yet, and therefore the antivirus detected it.

Nothing to do with this new forked "The Marvellous Suspender" extension, which has the ID ```noogafoofpebimajpfpamcfhoaifemoa```

**Comment by ghost** [comment]
@MeiRct ohh i now see that. Thanks for spotting. I likely know that the new folk will put in a google analysis script and is going through the code.

**Comment by tris543** [comment]
@gioxx think a mate of mine just opened it. Sorry about that. Asked him not to go on my pc without my permission, or to bring his laptop next time.

**Comment by Technetium1** [comment]
@tris543 the point of this project is to not have any analytics as explained at the top of the README https://github.com/gioxx/MarvellousSuspender/blob/master/README.md

**Comment by ghost** [comment]
@Technetium1 yep understandable. But this is a closed issue, Sooo yeah. also not my project so that doesn't really affect me and dont have plans to install it. :)
