### ISSUE TITLE
Chrome Web Store reports Marvellous was/is being downloaded, but no sign it's installed.

### ISSUE THREAD

**Issue by mkz7** [gioxx/MarvellousSuspender#46]
Attempted to install TMS into Brave browser from Chrome Web Store: 
https://chrome.google.com/webstore/detail/the-marvellous-suspender/noogafoofpebimajpfpamcfhoaifemoa?hl=en

No sign the extension has been installed.
"Add to Brave" button remains on-screen. 
If I click on the button I see the following error message:

"An error has occurred.
This item is already being downloaded and added into Chrome.
[Reload] [Close]"

Clicking either 'Reload' or 'Close' has no discernible effect.
TMS does not appear in my list of extensions.

The Marvellous Suspender (Chrome extension)
Brave browser (release version V1.20.103)
Mac OS Mojave

**Comment by sherkot** [comment]
I guess you've already tried to refresh the page to see if the button changes its text. 

In any case, if you press on the white piece of puzzle on the top-right to show all the extensions (pic 1), do you see TMS (pic 2)?

<img width="60" alt="puzzle" src="https://user-images.githubusercontent.com/16966007/107809207-fdfb5500-6d6a-11eb-9948-aa6f0ccd010d.png">

<img width="310" alt="tms" src="https://user-images.githubusercontent.com/16966007/107809208-fe93eb80-6d6a-11eb-8d5c-034611d705af.png">

If so, click on the pin to fix the extension in the top bar

**Comment by mkz7** [comment]
I guess one has to move fast on these, as I see that you've already closed it. (I was away for the weekend.) 
I see the Extensions icon you referred to, but no, TMS isn't shown when I click on it. The ones that display are the same ones whose icons also appear next to the Extensions icon.
Is it possible that the developer did something that installs TMS in Chrome (which I don't use) but doesn't in other Chromium-based browsers -- e.g., Brave (the one I do use)?
Thanks (& sorry for the delay),
MK
    On Friday, February 12, 2021, 01:54:59 PM EST, sherkot <notifications@github.com> wrote:  
 
 


I guess you've already tried to refresh the page to see if the button changes its text.

In any case, if you press on the white piece of puzzle on the top-right to show all the extensions (pic 1), do you see TMS (pic 2)?





If so, click on the pin to fix the extension in the top bar

**Comment by mkz7** [comment]
What I see is what's shown in the screenshot below. Clicking on the 'Reload' button just brings me back to the main TMS webpage.

It's looking to be a profile-related issue, as I was able to install the extension without issue in a new Brave profile. I haven't had this happen before with any Chrome extensions so I don't know what kind of 'conflict,' etc. that suggests might be occurring that's causing the installation failure in the original profile.

![image](https://user-images.githubusercontent.com/16544283/108124474-42da0100-7075-11eb-888c-d044ca78cc67.png)
