### ISSUE TITLE
Use Chrome API to screenshot tabs

### ISSUE THREAD

**Issue by Technetium1** [gioxx/MarvellousSuspender#48]
If we could avoid using a js lib (html2canvas) to take a screenshot that would be Marvellous, and probably faster!
https://developer.chrome.com/docs/extensions/reference/tabs/#method-captureVisibleTab

**Comment by Rojikku** [comment]
If you can gain a similar level of functionality from the built in API, it could help quickly clean/optimize code, and allow you to potentially remove those particularly long files.

**Comment by gioxx** [comment]
Hello guys.
During the yesterday evening session with @sherkot we have tried to use the official captureVisibileTab API without success.
I mean: we have obtained a result that is not what we expected. The API can be used only on the active tab and we can capture only visible part of the visited website. With html2canvas we can obtain a better result and capture - if necessary - the whole page.

We have updated the html2canvas library and removed the old dom-to-image no longer maintained. In the meantime we have modified permission request as reported here: https://github.com/gioxx/MarvellousSuspender/issues/6#issuecomment-783169228

I'm going to close this issue, sorry for that. If anyone would like to propose an alternative please fill another issue (or re-open this issue).
