### ISSUE TITLE
Session management tab jumps to top when I open a window

### ISSUE THREAD

**Issue by Pascal666** [gioxx/MarvellousSuspender#49]
* Extension version: v7.1.6.1
 * Browser name & version: Google Chrome Version 88.0.4324.150 (Official Build) (64-bit)
 * Operating system & version: Microsoft Windows Version 10.0.18363.1379

When scrolling through a saved session, when I click "open and suspend" or "open and load" on a window, the session management tab jumps to the top of the page so I have to scroll back down to where I was before.

**Comment by SWxEng** [comment]
Explain a problem with a picture or video
