### ISSUE TITLE
Import Great Suspender Whitelist

### ISSUE THREAD

**Issue by cholladay0816** [gioxx/MarvellousSuspender#5]
Is there any way to recover the Great Suspender whitelist and import it into the new extension?  I have a large amount of whitelisted domains that I need to retrieve.

**Comment by wchristian** [comment]
see #7

**Comment by cholladay0816** [comment]
@wchristian Sorry, I don't think the tab data is what I'm looking for.  I'm wondering where to find the whitelisted domain file that prevents the app from suspending certain pages, and how to extract that from TGS.
![image](https://user-images.githubusercontent.com/57429754/106947231-bbdd6e00-66ef-11eb-921d-5e92c4326794.png)

**Comment by wchristian** [comment]
oh jeeze, yeah that's more difficult and will require tech chops. you'll need to find the sqlite file that housed the tgs settings database and extract the data from it, maybe with a tool like https://sourceforge.net/projects/sqliteman/

**Comment by alagos** [comment]
I've tried finding the [extensions location](https://apple.stackexchange.com/a/170975/312743) (I suppose the path should be similar in lnx/win, but google is your friend) and I've checked [how to open those LevelDB files](https://stackoverflow.com/a/35142175/895789), but at the end of the day, it doesn't really worth (to me) the time to spend on recover that whitelist.
So I hope this be a good start point for someone really interested on recover them.

**Comment by cholladay0816** [comment]
I checked my `%LocalAppData%\Google\Chrome\User Data\Default\Local Storage` directory and it looks like `chrome-extension_klbibkeccnjlkjkiokjodocebajanakg_0.localstorage` was dropped after chrome flagged the extension as malware, so it may not be possible to retrieve my whitelist.  I'll try a deep scan with Recuva but the file's probably fried.

Edit: Recuva did not find any localstorage files, the whitelist is dead.

**Comment by gioxx** [comment]
Unfortunately TMS can't access to the old TGS data and recover the whitelist.
