### ISSUE TITLE
 Suggest a feature to choose which language

### ISSUE THREAD

**Issue by SWxEng** [gioxx/MarvellousSuspender#54]
hi

Suggest a feature to choose which language

Language selection menu In the extension settings
The Marvelous Suspender

See Example
![45454](https://user-images.githubusercontent.com/55116927/107859718-14291400-6e44-11eb-8b64-9972adc4a7ea.png)

**Comment by gioxx** [comment]
TGS / TMS use the default i18n API available in Google Chrome:
https://developer.chrome.com/docs/extensions/reference/i18n/
https://developer.chrome.com/docs/webstore/i18n/

Your idea / necessity was discussed in an old Chromium Extension Group thread on https://groups.google.com/a/chromium.org/g/chromium-extensions/c/rD0LLcSsyY8?pli=1, is interesting but - at the moment - we cannot rewrite chrome.i18n, we would like to fix TGS issues and consider to clean / upgrade the old code before thinking about features that are not "really critical" for all users.

That doesn't mean we won't evaluate this in the future, I hope you understand, I'm closing the issue at the moment and I invite you to use [Language switcher](https://chrome.google.com/webstore/detail/language-switcher/cecgfmnogmdnfaaenheimdknaohcbcai) (for example) if you want to make some tests.

Feel free to open again this issue if you have alternatives to suggest.

**Comment by SWxEng** [comment]
ok , Thank you
