### ISSUE TITLE
Extension permissions

### ISSUE THREAD

**Issue by cowbert** [gioxx/MarvellousSuspender#6]
Does this still require permission: "Read and Change all the data on the websites you visit"? It should only require read and change history (since it should basically just suspend the tab based on the history and tab stack order and replace it with the alias to the original uri).

**Comment by gioxx** [comment]
Sorry for the late reply @cowbert.
After @sherkot and I reviewed the code and did more testing together, we realized that access to all websites is only necessary for the screen capture feature offered within the extension.

if you don't use this function and you want to avoid that TMS access to all visited web sites you can certainly set the access property "on click". The extension will continue to work without any problem.

**Comment by ThisIsRobin** [comment]
> if you don't use this function and you want to avoid that TMS access to all visited web sites you can certainly set the access property "on click". The extension will continue to work without any problem.

Awesome, please make it your highest prio, when thinking about future changes to this tool, that opting out on this with "on click" will always be an option - thanks for the work you are doing!

Cheers!

**Comment by gioxx** [comment]
Hello guys!
Yesterday evening, me and @sherkot we have changed some details in the extension that now no longer requires full http/https access permissions during the installation phase, these will be required only when you go to enable screen capture.

If you don't grant the permission, the extension continue to works well without the ability to capture an image of the website before suspension, and the "screen capture" feature remain disabled.

Commit: https://github.com/gioxx/MarvellousSuspender/commit/c235004cffcb9ee5425a92fb590aa99b3daaf386

I hope this news makes you happy (and in a next occasion we will try to understand if we can also touch up further the permissions section) 😄

**Comment by Omar-Elrefaei** [comment]
Nice work. 🔥👍

**Comment by alexey-pelykh** [comment]
Awesome 🚀 ! When this version would be released via Chrome app store?
