### ISSUE TITLE
Current version on Chrome Web Store doesn't match the version on Github

### ISSUE THREAD

**Issue by ufukertenli** [gioxx/MarvellousSuspender#62]
* Extension version: 7.1.6.1_0
 * Browser name & version: Chrome 88.0.4324.182
 * Operating system & version: Windows 10

I have checked the update date on the Chrome Web Store and it shows that the extension was updated Feb 10th. However, when I checked the local source files on my computer, non of the .js files in my local storage are actually updated with the ones currently on GitHub (latest updated on May). Even though I am not a js person, I think I have seen traces of gsAnalytics etc. So, should I/we update the extension from source or will you be releasing this current version on the Web Store?

Thanks.

**Comment by gioxx** [comment]
Ciao @ufukertenli.
The version available on GitHub is a constant "work in progress", on Chrome Store I have uploaded the 7.1.6.1 but there are a lot of changes in the actual version. I have uploaded 7.1.6.2 (with these changes) on Chrome Store for beta users and I'm waiting the Google's approval process.

If this goes correctly and we don't notice problems during extension update on our Google Chrome, I will immediately submit 7.1.6.2 for all users and we need only to wait Google's public revision and publish process.

Keep calm and wait for 7.1.6.2, there will be a lot of good news! :bowtie: :pray:
