### ISSUE TITLE
FOR THE NEWCOMERS: How to import TGS tabs

### ISSUE THREAD

**Issue by wchristian** [gioxx/MarvellousSuspender#7]
You'll need to have notepad++ or a similar text editor with regex search and replace.

- install the marvellous suspender, open its options
- export the session into a text file
- open the text file with notepad++
- open search and replace and set "search mode" to "regular expression", then replace `chrome-extension.*uri=` with an empty string
- save the text file
- close all your tabs
- import the session from the saved file with "open and suspend"

**Comment by wchristian** [comment]
i made this as a separate issue to give more visibility to the question in #3, #5, https://github.com/greatsuspender/thegreatsuspender/issues/1175, https://github.com/greatsuspender/thegreatsuspender/issues/1309, https://github.com/greatsuspender/thegreatsuspender/issues/526

**Comment by ultragreg** [comment]
Marvellous installed, but I did not have an export option.

**Comment by wchristian** [comment]
@ultragreg 

- open settings ![image](https://user-images.githubusercontent.com/175467/106946491-72aa1000-6729-11eb-9b35-c26c83184eb0.png)
- mouse over current session ![image](https://user-images.githubusercontent.com/175467/106946534-82c1ef80-6729-11eb-8844-24878a89cf20.png)

**Comment by emmett13** [comment]
Thanks for posting this! So I'm a little confused about the steps—how do I get to the old, saved session of tabs from TGS? Is that the one I am supposed to edit and load? The way that it's written, it seems like I should just export the session I have open, but when TGS was pulled, it just removed all of those tabs, so I'm not sure how to get them open.

**Comment by wchristian** [comment]
@emmett13 you don't need the old session, just follow the steps, also see shots above

**Comment by ultragreg** [comment]
> @ultragreg
> 
> * open settings ![image](https://user-images.githubusercontent.com/175467/106946491-72aa1000-6729-11eb-9b35-c26c83184eb0.png)
> * mouse over current session ![image](https://user-images.githubusercontent.com/175467/106946534-82c1ef80-6729-11eb-8844-24878a89cf20.png)

Yes but I have no current session. I did not close my chrome since TGS shutdown.
I had a significant number of openned tabs (maybe more than 200)

I have tested with 2 others computer. Ok I have current session, export, but no 'chrome-extension.*uri=' in the txt file. No traces of previous tab suspended by TGS

**Comment by wchristian** [comment]
if you closed your tabs you'll want to reopen them via the history menu, and if you can't via that, then you'll need to find another solution involving TGS' sqlite file and a tool like sqliteman

![image](https://user-images.githubusercontent.com/175467/106948488-0ed51680-672c-11eb-9d7f-b942d2ebc641.png)

**Comment by mcchong** [comment]
For anyone else who like me, didn't have any saved sessions or similar in TGS, Session Buddy etc., and don't feel inclined to go digging through your history, this should help:
https://github.com/greatsuspender/thegreatsuspender/issues/1304#issuecomment-773534043

Basically, quit and open chrome, quickly open TGS options page before it gets disabled, and export your last recorded session, then you can do whatever you want (I imported it here and reopened everything, and will try and reduce my tabs before I uninstall here, but at least I can be confident I've saved my tabs consistently, if not the history associated with them).

**Comment by ultragreg** [comment]
> if you closed your tabs you'll want to reopen them via the history menu, and if you can't via that, then you'll need to find another solution involving TGS' sqlite file and a tool like sqliteman
> 
> 

Ok thanks, I will take a look for another solution

**Comment by mcchong** [comment]
> if you closed your tabs you'll want to reopen them via the history menu, and if you can't via that, then you'll need to find another solution involving TGS' sqlite file and a tool like sqliteman
> 
> ![image](https://user-images.githubusercontent.com/175467/106948488-0ed51680-672c-11eb-9d7f-b942d2ebc641.png)

How do I find the sqlite file?

**Comment by wchristian** [comment]
sorry, not my field of expertise, you'll need to browse around the other issue threads

**Comment by ultragreg** [comment]
> For anyone else who like me, didn't have any saved sessions or similar in TGS, Session Buddy etc., and don't feel inclined to go digging through your history, this should help:
> [greatsuspender#1304 (comment)](https://github.com/greatsuspender/thegreatsuspender/issues/1304#issuecomment-773534043)
> 
> Basically, quit and open chrome, quickly open TGS options page before it gets disabled, and export your last recorded session, then you can do whatever you want (I imported it here and reopened everything, and will try and reduce my tabs before I uninstall here, but at least I can be confident I've saved my tabs consistently, if not the history associated with them).

This works, thanks

**Comment by ThisIsSammysAccount** [comment]
Also good to note, it is important you start with an export of the current Marvelous Suspender session and don't just open a new text file in notepad. I tried with a new text file and it combined all my old tabs into a single window when importing. I assume it has to do with file encoding, the export just uses LF instead of CRLF at line endings.

**Comment by danielsharvey** [comment]
I use Session Buddy, so being able to clean individual URLs is helpful i.e. It has saved the suspended tabs thrown away when the extension was removed from the store.

On Mac I've used Automator to set up a "Services" menu script "Clean Great Suspender URL" which you run by selecting and processing the URL through a sed script with the regular expression noted in this issue:

```
sed -e 's/chrome-extension.*uri=//'
```

See [Clean Great Suspender URL.zip](https://github.com/gioxx/MarvellousSuspender/files/5929529/Clean.Great.Suspender.URL.zip)

**Comment by msva** [comment]
Btw, it would be nice to have a possiblity to somehow import saved sessions from (force-disabled) TGS :-/

**Comment by emmett13** [comment]
> For anyone else who like me, didn't have any saved sessions or similar in TGS, Session Buddy etc., and don't feel inclined to go digging through your history, this should help:
> [greatsuspender#1304 (comment)](https://github.com/greatsuspender/thegreatsuspender/issues/1304#issuecomment-773534043)
> 
> Basically, quit and open chrome, quickly open TGS options page before it gets disabled, and export your last recorded session, then you can do whatever you want (I imported it here and reopened everything, and will try and reduce my tabs before I uninstall here, but at least I can be confident I've saved my tabs consistently, if not the history associated with them).

^^^This was super helpful--I had some important tabs and it was going to be a drag to try to recover them. @ultragreg

**Comment by verglor** [comment]
For [Session Buddy](https://chrome.google.com/webstore/detail/session-buddy/edacconmaakjimmfgnblocblbcdcpbko) see https://github.com/greatsuspender/thegreatsuspender/issues/526#issuecomment-774369788

**Comment by JesusAtheist** [comment]
#42

**Comment by candrapersada** [comment]
> @ultragreg
> 
> * buka setelan ![image](https://user-images.githubusercontent.com/175467/106946491-72aa1000-6729-11eb-9b35-c26c83184eb0.png)
> * tetikus selama sesi saat ini ![image](https://user-images.githubusercontent.com/175467/106946534-82c1ef80-6729-11eb-8844-24878a89cf20.png)

Is it possible to export current sessions to bookmarks to use bookmark sync for other PCs?
