### ISSUE TITLE
Lots of browser tabs randomly disappeared

### ISSUE THREAD

**Issue by Destroy666x** [gioxx/MarvellousSuspender#70]
* Extension version: 7.1.6.1
 * Browser name & version: Chrome 88.0.4324.150
 * Operating system & version: Windows 10

I had around 80 tabs in a single window. I closed the laptop and when i opened it there were only around 40. Not completely sure if this extension caused it, but never had this issue and this is the only change I've made to Chrome except upgrading it during the last few months. Adding here just in case someone else has the same problem. And any clue how to possibly recover those?

**Comment by Technetium1** [comment]
@Destroy666x your best bet when any tabs are gone is to immediately try to CTRL+SHIFT+T and reopen them. I've not had this issue so the best I can do is refer you to `Session management` in the extension's options `chrome-extension://noogafoofpebimajpfpamcfhoaifemoa/history.html`. This is another place to look if that's not successful https://github.com/greatsuspender/thegreatsuspender/issues/526

**Comment by Destroy666x** [comment]
I recovered old ones using Session Buddy and some of newer important ones just from memory. I hope this won't happen anymore though. The newer ones weren't saved to "previous session" from this extension either BTW, since as I assume they're just saved when brwser is closed, here it wasn't.
