### ISSUE TITLE
Claims of the store version of the extension keeping analytics tracking?

### ISSUE THREAD

**Issue by vzvzxv** [gioxx/MarvellousSuspender#73]
https://github.com/greatsuspender/thegreatsuspender/issues/1175#issuecomment-790963980
A claim in a comment was made over on the original suspender repository that this repository does not match the version uploaded to the Chrome Web Store. Can you speak to these claims?

**Comment by Technetium1** [comment]
That comment is in reference to `deanoemcke` not `gioxx`. Please also see https://github.com/gioxx/MarvellousSuspender/issues/62

**Comment by xenithorb** [comment]
https://github.com/gioxx/MarvellousSuspender/compare/master...aciidic:master

It does looks like @gioxx did indeed miss some of the gsAnalytics references and various other analytics functions 

Whether what is live on MervellousSuspender is inert tracking-wise I am not sure.

**Comment by Technetium1** [comment]
@xenithorb can you direct link what you're talking about in regards to leftover analytics?

**Comment by gioxx** [comment]
https://github.com/greatsuspender/thegreatsuspender/issues/1175#issuecomment-793665826
