### ISSUE TITLE
Page refreshes before suspension

### ISSUE THREAD

**Issue by 2357532** [gioxx/MarvellousSuspender#77]
After today's update, suspending a tab now causes the page to refresh.

v7.1.6.2
Version 91.0.4466.2 (Official Build) canary (64-bit)
Windows 10 Pro 10.0.19042

- Choose suspend this tab now
- Page refreshes
- Tab suspends

The page refresh never happened in the past. It's a minor annoyance when suspending a tab manually.

**Comment by baz357** [comment]
Seems to be related to not saving the current position in YouTube videos anymore. The URL now always ends with t=0s where the previous version saved the current video position correctly.

**Comment by gioxx** [comment]
Ciao @2357532 and @baz357, can I ask if this problem happens with any URL visited? I'm using version 7.1.6.2 downloaded from the Chrome store, and trying to suspend a tab, it doesn't refresh before being suspended. Can I ask you to give me some test URLs that is giving you this problem?
Thanks in advance!
Giovanni.

**Comment by baz357** [comment]
> Ciao @2357532 and @baz357, can I ask if this problem happens with any URL visited? I'm using version 7.1.6.2 downloaded from the Chrome store, and trying to suspend a tab, it doesn't refresh before being suspended. Can I ask you to give me some test URLs that is giving you this problem?

Ciao Giovanni! I was able to reproduce the problem with https://www.youtube.com/watch?v=VfNVO6wwgDA several times just now. Let it play for a few seconds, then use the icon or hotkey to suspend the tab. The tab refreshes, the resulting URL then always ends with t=0s here.

What's weird though: when I tried it with another YouTube video earlier, it did work there.

**Comment by gioxx** [comment]
Great video choice (so much hype for the Loki series) 😏
About the problem: I can't reproduce it! If I go on YouTube (i'm connected with my account, are you?) and I suspend the tab with CTRL+S or clicking on "Suspend this tab now", TMS suspend immediately the tab without refreshing and the URL contains the correct timing (this is my example now: chrome-extension://noogafoofpebimajpfpamcfhoaifemoa/suspended.html#ttl=(118)%20Marvel%20Studios'%20Loki%20-%20Official%20Trailer%202%20(2021)%20Tom%20Hiddleston%2C%20Owen%20Wilson%20-%20YouTube&pos=0&uri=https://www.youtube.com/watch?v=VfNVO6wwgDA&t=83s).

Just for curiosity: have you tried on a clean Chrome profile with only TMS installed?

**Comment by baz357** [comment]
> About the problem: I can't reproduce it! If I go on YouTube (i'm connected with my account, are you?) and I suspend the tab with CTRL+S or clicking on "Suspend this tab now", TMS suspend immediately the tab without refreshing and the URL contains the correct timing

After reading your reply I tested many things: cleaning the Chrome cache, cleaning it even more with CCleaner, rebooting Windows, disabling some extensions... but it seems I finally found the culprit: TMS screenshots! I disabled screenshots in TMS and YouTube URLs are again saved correctly.

Please check if you can confirm that this is a bug. I love TMS screenshots but will leave this option off for now. :)
 
> Just for curiosity: have you tried on a clean Chrome profile with only TMS installed?

No, I don't want to risk harming my main (and only) profile with lots of tabs and extensions and settings. :-D

@2357532 Do you have screenshots enabled in The Marvellous Suspender? Does the problem persist if you disable that option?

**Comment by gioxx** [comment]
Bingo! With screenshot enabled I can reproduce the problem.
@sherkot we have to check why Html2Canvas library needs to refresh the tab to take screenshot and - more important - why this can't store page state correctly (time, page position, etc.).

**Comment by wchristian** [comment]
I see a lot of this in the console when trying to suspend a youtube url:

```js
webcomponents-sd.js:61 Uncaught TypeError: c.__shady_getRootNode is not a function
    at HTMLHtmlElement.getRootNode [as __shady_getRootNode] (webcomponents-sd.js:61)
    at HTMLBodyElement.getRootNode [as __shady_getRootNode] (webcomponents-sd.js:61)
    at HTMLElement.getRootNode [as __shady_getRootNode] (webcomponents-sd.js:61)
    at HTMLElement.getRootNode [as __shady_getRootNode] (webcomponents-sd.js:61)
    at kb (webcomponents-sd.js:32)
    at lb (webcomponents-sd.js:33)
    at Object.mb [as composedPath] (webcomponents-sd.js:33)
    at zE.get [as path] (desktop_polymer_inlined_html_polymer_flags.js:8648)
    at zE.get [as rootTarget] (desktop_polymer_inlined_html_polymer_flags.js:8642)
    at HTMLElement._onIronRequestResizeNotifications (desktop_polymer_inlined_html_polymer_flags.js:9519)
```

**Comment by 2357532** [comment]
Hi. It's all pages, not just youtube. I have 'capture top of screen only' set and 'high quality capture' unchecked. Additionally, I have 'apply chrome's built in memory-saving... ' set.

I gave canary as the chrome version, but it also happens with stable chrome.
