### ISSUE TITLE
Importing from TGS

### ISSUE THREAD

**Issue by mohseninima** [gioxx/MarvellousSuspender#8]
I was able to copy the `chrome-extension_klbibkeccnjlkjkiokjodocebajanakg_0.indexeddb.leveldb` and `chrome-extension_klbibkeccnjlkjkiokjodocebajanakg_0.indexeddb.blob` folders from the Chrome AppData folder. Is there any way to import these folders into TMS to get my tabs back?

**Comment by wchristian** [comment]
see #7

**Comment by mohseninima** [comment]
> see #7

That seems to work only if the tabs were not auto removed when TGS was disabled.

**Comment by jhyot** [comment]
@mohseninima If you haven't uninstalled The Great Suspender yet, it will still be on when restarting Chrome until Chrome checks and disables it (every start).

That means you can export your TGS session like this:

1. Completely quit Chrome (close all windows)
2. Turn off your internet connection
3. Start Chrome, check in extensions settings, TGS should be there and activated.
4. Go to TGS settings and export your session.

You should be able to import this exported session in TMS then.

If you don't have TGS installed anymore, you could sideload the safe open source version again and then export (google for instructions how to sideload)
