### ISSUE TITLE
v7.1.6.2 from Chrome Web Store breaks Screen Capturing settings

### ISSUE THREAD

**Issue by PorridgePi** [gioxx/MarvellousSuspender#81]
* Extension version: `v7.1.6.2 (from Chrome Web Store)`
 * Browser name & version: `Chrome 89.0.4389.114 (Official Build) (x86_64)`
 * Operating system & version: `macOS Version 11.2.3 (Build 20D91)`

In v7.1.6.2, when I try to change the Screen Capturing settings, the option will be selected briefly and immediately return to default (Disabled).

I checked console and found this error:
`Unchecked runtime.lastError: Extension must have file access enabled to request 'file:///*'.`

After reinstalling it from Chrome Web Store, the issue persisted.
After downgrading to v7.1.6.1, this issue is not present.
This issue is not present either in v7.1.6.2 from GitHub.

Apparently, in the GitHub version, when I select an option in Screen Capturing, a popup like the one below will appear. It did not appear for the one I installed from Chrome Web Store.
<img width="457" alt="Popup to request permissions" src="https://user-images.githubusercontent.com/34623167/113484217-b460f800-94d9-11eb-84b9-350b1e544059.png">

Therefore, it seems like the version submitted onto Chrome Web Store may have some permission settings broken.

Hopefully this is a bug and not my own problem.

Thank you!

**Comment by pantantrollo** [comment]
Hi @PorridgePi 

It can, I am not sure, that by default the extensions from the google store, have the access permission to file url, deactivated.

![image](https://user-images.githubusercontent.com/49453082/113484916-3128ad80-94ab-11eb-8148-a816a232ecd1.png)

In my case, with the updated version from the web store google, the same thing you describe happens, until said permission is activated, which is solved, and the screenshot works

**Comment by PorridgePi** [comment]
Hi @pantantrollo

Thank you for your reply.

Indeed, after I enabled that setting in the extension details in Chrome, the popup requesting for permissions will appear when I change the Screen Capturing setting. 

<img width="702" alt="Chrome Extensions Details" src="https://user-images.githubusercontent.com/34623167/113496794-bfdf0e00-952f-11eb-8765-2aa166912f88.png">

While my issue is now fixed, I would not close the issue because I think it is still a bug.

**Comment by gioxx** [comment]
Ciao @PorridgePi 
Tried on a clean profile of Chrome, I can confirm the bug and I can't understand why the problem appears only on Chrome Store version (is the same of GitHub) but I will investigate with @sherkot, we will fix this problem on a next version of TMS.

**Comment by awestbrook09** [comment]
### **Giving it access to file URLs fixed it for me.**

I was experiencing the same issue. Received the same error in the console: 
**Unchecked runtime.lastError: Extension must have file access enabled to request 'file:///*'.**


> ![image](https://user-images.githubusercontent.com/49453082/113484916-3128ad80-94ab-11eb-8148-a816a232ecd1.png)
> 
> In my case, with the updated version from the web store google, the same thing you describe happens, until said permission is activated, which is solved, and the screenshot works

**Comment by sherkot** [comment]
Fixed: https://github.com/gioxx/MarvellousSuspender/commit/4060cce3b6414915db19b1b617e6059c6793278d
