### ISSUE TITLE
Auto saving current session daily.

### ISSUE THREAD

**Issue by markOteams** [gioxx/MarvellousSuspender#94]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: v7.1.6.2
 * Browser name & version: Chrome Version 89.0.4389.114 (Official Build) (64-bit)
 * Operating system & version: Windows 10 20H2 Build 19042.906

And please also do a search for your request/bug before create a new one thanks!

Request for a feature, can you please make it possible to automate saving of the current session (with a variable for todays date)?

Thank you
Mark.

**Comment by sherkot** [comment]
Related to #71

**Comment by napolux** [comment]
Duplicate of #71. Closing it.
