### ISSUE TITLE
Can't pause suspension of a tab immediately after unsuspending it until switch to another tab first

### ISSUE THREAD

**Issue by MindCaged** [gioxx/MarvellousSuspender#97]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: v7.1.6.2
 * Browser name & version: Chrome 89.0.4389.114
 * Operating system & version: Windows 7 64-bit

And please also do a search for your request/bug before create a new one thanks!

Okay, I tried to track down what was causing this, but I figured out that if I un-suspend a tab that was suspended, then try to select the "Not now" option from the menu to prevent it from being auto-suspended, it won't let me select the option. I have to switch to another tab and then back to get it to respond.

Steps to reproduce:
* Suspend a tab
* Unsuspend it
* Try to select "Not now" from the Marvelous Suspender menu.

**Comment by gioxx** [comment]
Duplicate (already fixed): #86 (already available on GitHub or you have to wait TMS 7.1.6.3 for Chrome Store).
