### ISSUE TITLE
Can't activate the screenshot function

### ISSUE THREAD

**Issue by humanafterallwav** [gioxx/MarvellousSuspender#99]
* Extension version: 7.1.6.2
 * Browser name & version: Chrome 90.0.4430.72
 * Operating system & version: Windows 10 64-bit
  
 Hi! Great extension, the only problem i found so far is the fact i can't activate the screenshot function. I click on "disabled" to see the other settings, click on any other one but it switches back to "disabled" in a fraction of a second. Does the same if i use the arrows to switch settings.

**Comment by gioxx** [comment]
Ciao @humanafterallwav, it's a know bug of the Chrome Store version (very strange because the package on GitHub works perfect), please follow this: https://github.com/gioxx/MarvellousSuspender/issues/81
